### ISSUE TITLE
Script "freezing" with latest version of Nox?

### ISSUE THREAD

**Issue by raspberrytealeaf** [29988122/Fate-Grand-Order_Lua#115]
I'm not sure how to describe this behavior, cause I've never seen it happen in person. I always discover it when I come back [x] hours later.

I upgraded to the latest version of Nox recently cause I heard the date issue is fixed. But after upgrading, I can't seem to leave the bot running for multiple hours at a time without the script breaking or pausing. The most common place it seems to "pause" is on the drops/exp/etc screens after battles. I'll come back and it's on the drops screen.

If I click the next button for it, it'll continue on without any issues, but I don't know what happened that made it get stuck.

**Comment by ParasiteEve** [comment]
Happens to me, I have to check every hir

**Comment by ryuga93** [comment]
>https://github.com/29988122/Fate-Grand-Order_Lua/issues/109
 Side notes: I have no idea it's because I updated Nox to 6.2.5.3, or I updated Ankulua to 8.0.5.
The performance of recognition is VERY FAST now. You guys gotta give it a try.

There might be performance difference with the newest version for either Nox or Ankulua. Try to update to newest Ankulua.

**Comment by raspberrytealeaf** [comment]
I'm using both Nox 6.2.6.0 and Ankulua 8.0.5 already. :(

**Comment by TheIanator** [comment]
I think when two or move servant get bond up at the same time, or when you get a master/mystic code level it takes an additional click to get though, could this be it?

**Comment by raspberrytealeaf** [comment]
Afaik, the script already accounts for that. I've gotten servant bond level rewards (aside from CEs for lvl 10) w/o having this issue.

**Comment by potchy** [comment]
We'll probably need a video to understand what's going on.

**Comment by 29988122** [comment]
IRRC, I did add a edge case check for servant Kizuna LVL up/Mystic Code LVL up

Maybe
>potchy
should take a look at it 

or

We just wait for our debug logging to be completed..

**Comment by TryBane** [comment]
We have a case that checks for bond level up, but only 1 in any instance. And not when Mystic Code levels up. I implemented a different method during this particular section where it just continuously clicks about 12 times, which is enough to get through all of that assuming 5 bond ups and a mystic code up, then waits to see if friend request screen comes up.

**Comment by potchy** [comment]
I second @TryBane's idea.
Clicking the screen X number of times after `result.png` shows up is good enough, faster and just easier to implement, honestly.

**Comment by potchy** [comment]
Hey, I managed to get screenshots from the Bond CE screen.

![screenshot_2018-12-22-19-59-17](https://user-images.githubusercontent.com/4316326/50379009-9a12f100-0625-11e9-91fc-991a7c5da1ae.png)
![screenshot_2018-12-22-19-59-22](https://user-images.githubusercontent.com/4316326/50379008-9a12f100-0625-11e9-862d-775307f66771.png)

**Comment by TryBane** [comment]
That should be enough I think. The clicking for me is a long enough time to click through the first section, then we just need to image search for clicking "close". I believe we should search for the star image, no writing, to make it work on all versions not just EN. We can have a slight increase in region we are searching in so that if things get added it won't cause issues. Then just click the top left.

**Comment by ArianTerra** [comment]
Same problem here. I have to skip results screen every time. After battle script just stalls at results screen.

**Comment by TryBane** [comment]
Is that using the most recent version of the script? I believe I have solved a normal bond level up and mystic code level up. The only currently unhandled case is when you get a max bond CE.

**Comment by ArianTerra** [comment]
Yes, yesterday I downloaded the most recent version. Everything worked fine except skipping the results screen and support selection. When battle ended the script just stuck at results screen. Bond lvl up screen or something like that hasn't appeared. So I skipped it by myself and it started the quest again. When it clicked the quest button it stuck again, however I set support selection to "first".
Today I re-downloaded the script and now everything don't work except for quest selection function :/
Sorry for my English btw

**Comment by TryBane** [comment]
Nevermind, I didn't make a change because it should still work without issue selecting a support. Especially if it is to select first. Can I see your configuration if you can get a screenshot?

**Comment by TryBane** [comment]
I can tell you right now that it is PRECISELY why. The aspect ratio of your screen is so important because it determines the locations of the clicks, where it looks for images, and uses it to scale the image it sees and tests it against the image saved. If your resolution is even slightly off, it won't work.

Give me 2 minutes here I have to make one adjustment but you can give my own branch a try. I haven't been able to test to ensure there are no bugs but I have a friend who has been able to use it with different aspect ratios and it works.

[Here](https://github.com/TryBane/Fate-Grand-Order_Lua/tree/TryBane-Resolution-Scaling)

**Comment by ArianTerra** [comment]
Now there is another error:
![screenshot_20181227-184511_2 2](https://user-images.githubusercontent.com/33029096/50487902-affb2a00-0a08-11e9-9a4d-0f4c783ca7ae.png)

**Comment by TryBane** [comment]
That's an easy fix, one second and I'll update this message when it's fixed...

**Comment by ArianTerra** [comment]
No problems :D
So something went wrong again:
![screenshot_20181227-185955_2](https://user-images.githubusercontent.com/33029096/50488245-36643b80-0a0a-11e9-9242-d8b20e03b51a.png)

**Comment by TryBane** [comment]
Sorry, didn't get a notification. I fixed it.

**Comment by ArianTerra** [comment]
There is no errors now but it still doesn't work for me :(
After clicking ok nothing happened. I changed resolution via adb again and it still only clicks quest button.
I think my phone is the main problem so I'm going to test your script on my 1280x800 tablet tomorrow. I'll reply if it works or not.
Thanks for your help. Hope my English is good enough :d

**Comment by ArianTerra** [comment]
Hi! I've tried your script on my Asus Z380M tablet (1280x800, 16:10 or 8:5). So it has the same problem as my phone. However, while testing I noticed this tiny red rectangle (sorry for photo, my volume keys are slightly broken):
![img_20181228_162313](https://user-images.githubusercontent.com/33029096/50519825-6e7c8480-0ac5-11e9-99a0-2814145e8953.jpeg)
It appeared for one second and then gone.

**Comment by vit2657** [comment]
I also gave a try to your modified version with screen resolution on my poco f1 @TryBane (which has weird resolution of 1080 x 2246). Currently having same problem as the comment above.
Although I'm mainly using this script on Nox, I will be happy to help you test your modifications with my device if needed (I'm only using it for development anyway).

**Comment by TryBane** [comment]
As an update, I've gotten a possible solution implemented in the current build located in the same place. Give it a try and tell me if anything doesn't work appropriately. Should that be the case, please turn DebugMode to true and return with screenshots so I can further investigate what might be causing the problem.

**Comment by ArianTerra** [comment]
Still have the same problem :(
Some info from debug mode:
**If launched from battle screen**
Resolution: X: 2043 Y: 1080 (Real resolution is 2280x1080)
![screenshot_20181229-083221](https://user-images.githubusercontent.com/33029096/50538318-67617f00-0b76-11e9-97b9-a8618becf1a3.png)
Offset and first red box:
X: 240 Y: 0
![screenshot_20181229-140133](https://user-images.githubusercontent.com/33029096/50538349-df2fa980-0b76-11e9-9cf2-825b8be39577.png)
Second box:
![screenshot_20181229-140148](https://user-images.githubusercontent.com/33029096/50538356-143bfc00-0b77-11e9-81c1-91fa6f56414d.png)
Third: 
![screenshot_20181229-140205](https://user-images.githubusercontent.com/33029096/50538361-464d5e00-0b77-11e9-83fe-f20142186301.png)
The last one:
![screenshot_20181229-140220](https://user-images.githubusercontent.com/33029096/50538366-549b7a00-0b77-11e9-8292-d98b5f32437a.png)
**Main menu**
First red box after clicking OK
![screenshot_20181229-082424](https://user-images.githubusercontent.com/33029096/50538382-b0fe9980-0b77-11e9-8386-3e45a64d08eb.png)
The only red box in the support menu:
![screenshot_20181229-082429](https://user-images.githubusercontent.com/33029096/50538387-db505700-0b77-11e9-832f-d87dd0a48b39.png)

**Comment by TryBane** [comment]
Alrighty and this is with the more recent change I've made? If so, this is going to be a bit annoying.

**Comment by TryBane** [comment]
Okay, I am not entirely sure what is going on in your case as far as how your phone decides how to position the game but your phone is dumb. However, I do at least have a solution specifically for you that you can use. All you need to do is make xOffset equal to 300. Right now it gets set to 240 because the instances I've run across where the resolution isn't 16:9, it takes the extra space and simply cuts it in half dividing that extra space between both sides of the screen.

And so I calculate that total space, then divide it by 2 to get the offset I need. In your case however, the total extra space is 480. Instead of dividing this in half and splitting that onto both sides, it gives one side 300 pixels of bar and the other gets 180. I haven't a clue as to why.

If you make the offset what i just said, it should be fine. To do this, open your FGO_EN_REGULAR file from my repo and at the top you can delete the entirety of calculation I do when setting to xOffset (do NOT delete the script and compare that is directly under it) and replace that whole calculation with 300. I will continue to look for a solution, but it just seems dumb. Rather than have you constantly trying to figure it out I just figure give you the softfix for now.

This is a solution for anyone who doesn't have a 16:9 resolution but rather than give each individual an offset to use specifically for them, I wanted to make an algorithm that can do that automatically. Sadly, instances like these exist. I'll have to try figuring out another solution or improve the one I've got to consider non-even distribution of bars.

**Comment by TryBane** [comment]
All I did to see what the ACTUAL numbers were on each side was bring a single image he posted into this [image editing site](http://www.online-image-editor.com/), and resized it to 720 on the height (keep aspect ratio option turned on). Make sure you hit "Apply" then choose the Crop option. A red box will pop up, which you can click and drag the center of to move, and clicking slightly inside the box at one of the edges will move that particular edge/corner so you can resize it. I dragged it to the left, and resized it till it was approximately the right size of the left part of the screen. Look at the Width of the crop box on the left side and double that number.

That is all you need to do to determine the exact offset value you need (you may be able to use an easier method than this but this was the one I used). It is important to note that it is the LEFT side you need to measure, not the right. And if someone's aspect ratio results in a set of bars on the top and bottom, it is the TOP that needs to be measured in those cases.

**Comment by TryBane** [comment]
Which btw, your eyeballing is REALLY accurate. The measure I got from resizing your screenshot to 720 was 137, which doubled is 274 (for those that don't want to math). So being only 6 pixels off is really impressive :D

**Comment by TryBane** [comment]
One thing I realize for an instance like how you have a notch on your device, is that if you flip the device over it might suddenly not work. I don't have an idea as of yet on how to fix this potential issue, so do me a favor and check if that DOES cause an issue, and let me know whether it does or not cause whatever solution I may make regarding your guys' cases will NEED that info.

**Comment by vit2657** [comment]
Yeah, it does not work if I flip it, which is logically correct. It just constantly spams a toast with info about xOffset and yOffset (280 and 0 for now) trying to re-determine it probably.
![screenshot_2018-12-29-17-45-35-578_com aniplex fategrandorder en](https://user-images.githubusercontent.com/18238005/50539954-9802e200-0b91-11e9-84ed-3a0bc133e8ed.png)

One thing to note is that a black bar on the side with the smallest offset is a safe space so the game won't render there cause of rounding corners of the screen.

**Comment by vit2657** [comment]
And when I removed a hard coded value, the offset initially calculated appeared to be rather big (217 currently).
![screenshot_2018-12-29-17-53-14-704_com aniplex fategrandorder en](https://user-images.githubusercontent.com/18238005/50540009-b7e6d580-0b92-11e9-8066-cb8b048138f5.png)

**Comment by TryBane** [comment]
Yeah, that is because of the lack of equal distribution of the bars. I think I may have thought of the concept of a solution for all of this, but actually coding it might take a bit. Potchy said before that resolution algorithms are his thing, and after he gave the go ahead I started to work on this particular iteration myself. Maybe he might have an answer that I don't have, but I will be looking into seeing about getting my own solution to work appropriately. For now, I suggest keeping the device flipped as it was, or modifying the script in order to handle the opposite orientation. Whichever is most comfortable for you.

I may ask for your help about testing a later version when I get around to wrapping my head around the idea that I have and actually implementing the first version of it. Thanks for your patience and feedback about the issue you were having. It has helped me understand some of the problems that trying to take care of screen resolution comes with :D

**Comment by ArianTerra** [comment]
@TryBane Thank you for your effort! Now everything works perfectly!

**Comment by TryBane** [comment]
Alright, that sounds good. Did you specifically run into the issue? Or just noticed someone had one? It isn't related to the resolution issue if that is a thought. But regardless, if it works on Nox and you don't have an issue running it there, then sounds good to me! I'll still see about getting this solved for those would-be phone users of the script when there is a bloody notch in their device (which I may be getting one with the S10+ >.> )

**Comment by 29988122** [comment]
Tested myself, servant Kizuna level up screen can be solved by the new ContinuousClick().
That leaves us CE gain screen.


Can anybody tell me the sequence of the whole result screen(edge case included?)
What I know now(could be incorrect):
```
Servant Kizuna increasing animation
Servant Kizuna level up (OPTIONAL)
Master and Cloth Exp
Reward List
Event Reward List
~~~~~~~~Long Loading~~~~~~~~~
Stage Reward(Quartz, Mana Prism, etc)
```
Where is CE gain located?

**Comment by ryuga93** [comment]
https://youtu.be/Ek3Se0sAi8c?t=128

After Kizuna Level Up

**Comment by TryBane** [comment]
You actually could use the favorite button. It is in the EN server since the Thanksgiving update I believe.

**Comment by vit2657** [comment]
@TryBane did you remove your branch with resolution fix or did you merge it somewhere?

**Comment by TryBane** [comment]
Yeah, it was fully merged after the instances with you two and another thread were resolved. Still have to come up with a way to deal with notches but we have a plan for that!
