### ISSUE TITLE
NP spam not active when auto skill enabled

### ISSUE THREAD

**Issue by minalinskychan** [29988122/Fate-Grand-Order_Lua#193]
this is my setting 

--AutoSkill
Enable_Autoskill = 1
Skill_Confirmation = 0
Skill_Command = "abc,#,a3bcx11abcef,#,j"

--NoblePhantasm Casting
Battle_NoblePhantasm = "spam" 

when i set Enable_Autoskill = 0, the tap for np spam is actived (there tap in np selection area)

but when i set Enable_Autoskill = 1, even the np is ready, the np is not selected.

sorry for bad english.

**Comment by forgehe** [comment]
Try adding the NPs you want in the Skill_Command

You can activate NPs using 4 5 6

That's works for me. 
I have Battle_NoblePhantasm = "disabled" but Skill_Commands set to use NPs to clear battles

**Comment by 29988122** [comment]
Fixed in https://github.com/29988122/Fate-Grand-Order_Lua/pull/197

**Comment by RalphixJP** [comment]
Hi it seems like there was a fix for this issue, but I'm still having this problem as of late. I play on the JP server
